Issue/731 randomization
TorXakis/TorXakis pull request #737
Opened 2018-06-19 15:50 UTC by pjljvandelaar

related to #731

2018-06-20 07:00 UTC, pjljvandelaar commented
@keremispirli what is the performance impact?

2018-06-20 07:03 UTC, keremispirli commented
@pjljvandelaar The branch still has conflicts; could you merge from develop? Then I'll start a benchmark to see performance.

2018-06-20 07:05 UTC, pjljvandelaar commented
@keremispirli why is semaphoreci absent?

2018-06-20 07:07 UTC, keremispirli commented
Possibly another webhook glitch; let's see if we have it when `develop` is merged.

2018-06-20 07:25 UTC, pjljvandelaar commented
Seems I missed some push or pop
....

2018-06-20 11:07 UTC, pjljvandelaar commented
Indeed missed hlint issue...
Why is semaphoreci absent as checker?

2018-06-20 12:04 UTC, pjljvandelaar commented
Fine on appveyor!

2018-06-20 12:56 UTC, keremispirli commented
The webhook looks successful, I redelivered it twice but for some reason SemphoreCI continued ignoring this branch.
Then I discovered a tiny (+) sign next to "Branches" title on the project page of TorXakis, which I could enable this branch. Now it's running.

2018-06-21 11:10 UTC, pjljvandelaar commented
No failing tests @ appveyor... just out of time.
Should we rerun and make it in time or just accept (earlier commits did succeed)

2018-06-21 11:21 UTC, capitanbatata commented
I just restarted appveyor. I guess this is another reason for biting the bullet and replacing the current compiler. We might gain a lot of time by avoiding long compilation times. I'm going to benchmark how much time we will gain after I'm done with the cleanup (Friday or Monday).

2018-06-21 14:05 UTC, keremispirli commented
Meanwhile I'm running the benchmarks on this version. Stay tuned.

2018-06-21 14:13 UTC, pjljvandelaar commented
@keremispirli I am mainly interested in the difference between IncrementBins and IncrementChoice on this branch: the most equal comparison imho.

2018-06-21 14:14 UTC, pjljvandelaar commented
@capitanbatata seems something wrong at appveyor: the others are canceled, yet this build doesn't start ;-(

2018-06-21 14:22 UTC, capitanbatata commented
I restarted it again. Let's see...

2018-06-21 14:23 UTC, capitanbatata commented
Ok, now it started right away...

2018-06-21 14:44 UTC, keremispirli requested changes
@pjljvandelaar With this version, I cannot assign `param_Randomization` to `IncrementBins`.

```
TXS >> param param_Randomization IncrementBins
TXS >>  No parameter: param_Randomization
```
Note that the error message is misleading; it says "No parameter" but actually error happens because IncrementBins is not recognized.

```
TXS >> param param_Randomization TrueBinsa
TXS >>  No parameter: param_Randomization
```

It does work for different randomization parameters though:
```
TXS >> param param_Randomization
TXS >>  param_Randomization = IncrementChoice
TXS >> param param_Randomization TrueBins
TXS >>  param_Randomization = TrueBins
```

2018-06-21 15:03 UTC, keremispirli commented
Another issue: There's no guarantee that the `.torxakis.yaml` file at the root of the repo will be used for configuration. In order to set default randomization to `IncrementBins`, L60 in `\sys\solve\src\Solve\Params.hs` should also be changed to `IncrementBins`.

2018-06-21 17:48 UTC, pjljvandelaar commented
Appveyor again stopped after 1 hour. 
I noticed it did not use the stack cache: everything was build from scratch...

2018-06-22 06:37 UTC, pjljvandelaar commented
@keremispirli I can't reproduce
```
TXS >>  TorXakis :: Model-Based Testing

TXS >>  txsserver starting: "NLYBSTQVP4NB77Y.code1.emi.philips.com" : 63044
TXS >>  Solver "z3" initialized : Z3 [4.8.0 - build hashcode a12af4a619a0]
TXS >>  TxsCore initialized
TXS >>  input files parsed:
TXS >> param
TXS >>  param_ImpRel = IOCO
TXS >>  param_IncrementChoice_IntPower = 4
TXS >>  param_IncrementChoice_IntRange = 65536
TXS >>  param_IncrementChoice_MaxGeneratedStringLength = 10
TXS >>  param_InputCompletion = ANGELIC
TXS >>  param_RandSolve_IntHalf = 1000
TXS >>  param_RandSolve_IntNum = 5
TXS >>  param_Randomization = IncrementBins
TXS >>  param_Sim_inputEager = 0
TXS >>  param_Test_inputEager = 3
TXS >>  param_TrueBins_Next = Linear
TXS >>  param_TrueBins_NrOfBins = 10
TXS >>  param_TrueBins_StringLength = 6
TXS >>  param_TrueBins_StringMode = Regex
TXS >>  param_max_rand_depth = 4
TXS >>  param_Sim_deltaTime = 2000
TXS >>  param_Sim_ioTime = 10
TXS >>  param_Sut_deltaTime = 2000
TXS >>  param_Sut_ioTime = 10
TXS >> param param_Randomization TrueBins
TXS >>  param_Randomization = TrueBins
TXS >> param param_Randomization IncrementBins
TXS >>  param_Randomization = IncrementBins
TXS >>
```

2018-06-22 06:42 UTC, pjljvandelaar commented on sys/solve/src/Solve/Params.hs
> +                                                                                  || (s == show IncrementBins) )
Added IncrementBins to check function, so don't understand why not accepted. Will investigate tomorrow.

2018-06-22 06:43 UTC, pjljvandelaar commented on sys/solve/src/Solve/Params.hs
> +                                                                                  || (s == show IncrementBins) )
Made remark yesterday, yet review was not started.....

2018-06-22 06:56 UTC, pjljvandelaar commented
Do we want duplication in test code?
It turns out that I also have to change the test code, now that I changed the default value: it is not derived from the original code.
Will send commit soon.

2018-06-22 08:13 UTC, keremispirli commented
Strange. I run the script which runs `stack install`. I had still suspected that, so tried to reinstall but stack just copied the same executables. I'll try again with this version.

2018-06-22 09:13 UTC, pjljvandelaar commented
After 28:15 minutes the actual tests start @ appveyor.
Semaphoreci is finished in 25:57 minutes...

I think the new randomization solution is slower, yet better distributed.
The question is how further?
Let's discuss on Monday!

2018-06-22 09:27 UTC, keremispirli commented
I'll run a no-test build with lts 11.5 so that it succeeds and caches `.stack-root`. That should cut some of the build time.

2018-06-22 09:40 UTC, pjljvandelaar commented
@keremispirli Great!

2018-06-22 11:12 UTC, keremispirli commented
Looks like everything was already cached. So this failing build was merely a cache-miss. I restarted it; now it fetched `.stack-root` and is building with it.

2018-06-22 12:10 UTC, pjljvandelaar commented
Just in Time: 59 min and 15 seconds!

2018-06-22 12:11 UTC, pjljvandelaar commented
@keremispirli Is your review solved?
If so, please accept!

2018-06-22 12:44 UTC, keremispirli commented
It's solved and benchmark of IncrementBins is also finished, but I'm still waiting for benchmark of IncrementChoice. Should I accept regardless?

2018-06-22 13:45 UTC, pjljvandelaar commented
No, let's discuss on Monday!

2018-06-25 10:07 UTC, keremispirli commented
Here are the benchmark results: [Randomization_IncChoice_vs_IncBins.xlsx](https://github.com/TorXakis/TorXakis/files/2132572/Randomization_IncChoice_vs_IncBins.xlsx)

Key outcomes:
 - "_Hiding/match Int_" is 526.6 % faster
 - "_Real World/Multiple Conrol Loops Stepper_" is 58.68 % faster
 - "_Real World/Customers and Orders_" is 73.5% **slower**
 --> This is because random strings generated by IncrementBins are longer than the ones from IncrementChoice.
 - All "_Sequence/sequence with a 10 integer channel_" cases are ~50 % **slower**
--> Because there are more bins tried.

2018-06-25 10:09 UTC, keremispirli approved these changes

2018-06-25 10:10 UTC, merged